### ISSUE TITLE
Doesn't work with nushell

### ISSUE THREAD

**Issue by VarLad** [ajeetdsouza/zoxide#274]
Followed the instructions from README.md
Here's my `config.toml` file for nushell

```toml
skip_welcome_message = true
startup = ["zoxide init nushell --hook prompt | save ~/.zoxide.nu", "source ~/.zoxide.nu"]
complete_from_path = true
```

Here's my error (from Alacritty)
```
error: 'nushell' isn't a valid value for '<shell>'
	[possible values: bash, fish, posix, powershell, xonsh, zsh]

USAGE:
    zoxide init <shell> --hook <hook> --cmd <cmd>

For more information try --help
error: Save requires string data
  ┌─ shell:1:37
  │
1 │ zoxide init nushell --hook prompt | save ~/.zoxide.nu
  │                                     ^^^^ consider converting data to string (see `help commands`)

error: Can't load source file. Reason: No such file or directory (os error 2)
  ┌─ shell:1:8
  │
1 │ source ~/.zoxide.nu
  │        ^^^^^^^^^^^^ Can't load this file

```

This is on Fedora 34 x86_64 GNOME
